// src/App.vue
<template>
    <div>
        <Form v-if="this.votingOpen === false" @onSubmit="onSubmit"/>
        <VotingCard v-else-if="this.votingOpen" :title = "title" :state = "votingCardState" :votes = "votes"/>
    </div>
</template>

<script>
import VotingCard from './VotingCard'
import Form from "./Form"
import store from "./store"
export default {
    name:"App",
    data: ()=>({
        votingOpen: false,
        title:'',
        votes:[],
        votingCardState: 'open'
    }),
    components: {Form, VotingCard},
    methods:{
        onSubmit(){
            this.title = store.title
            this.votes = store.votes
            this.votingOpen = true
        }
    }
}
</script>

<style>

</style>

// frameworks-voting/src/stories/App.component.ts
import { Component} from '@angular/core'
import {DataService} from "./Data.service"
@Component({
    selector: 'App',
    template: `
    <div *ngIf="votingOpen === false; else votingcard">
    <Form (submitEvent)="onSubmitEvent()"></Form>
    </div>
    <ng-template #votingcard>
        <VotingCard [title] = 'title' [state] = 'state' [votes] = 'votes'></VotingCard>
    </ng-template>`
  })
export default class AppComponent {
    votingOpen = false
    title = ''
    state = 'open'
    votes: Array<{option:string, count:number}> = []
    constructor(public data:DataService){}
    onSubmitEvent(){
        this.title = this.data.getTitle()
        this.votes = this.data.getVotes()
        this.votingOpen = true
    }
}
