// src/Results.vue
<template>
  <div>
      <ol>
          <li v-for="vote in votes" :key = "vote.option">{{vote.option}} - {{vote.count}} votes</li>
      </ol>
  </div>
</template>

<script>
export default {
    name: 'Results',
    props: {
    votes: {
        type: Array,
        required: true,
    },
  },
}
</script>

<style>

</style>

// frameworks-voting/src/stories/Results.component.ts
import { Component, Input} from '@angular/core'

@Component({
    selector: 'Results',
    template: `
    <ol>
    <li *ngFor="let vote of votes">{{vote.option}} - {{vote.count}} votes </li>
    </ol>
    `
  })
export default class ResultsComponent {
    @Input()
    votes: Array<{option:string, count:number}> = []
}
