// src/VotingCard.vue
<template>
    <div>
    <h1>{{title}}</h1>
    <Booth v-if="state === 'open'" :options = 'retrieveOptions()' @onVote="onVote"/>
    <Results v-else-if="state === 'closed'" :votes = "votes"/>
    </div>
</template>

<script>
import Booth from "./Booth"
import Results from "./Results"
export default {
    name: 'VotingCard',
    components: {Booth, Results},
    props: {
        title: {
            type: String,
            required: true,
        },
        state: {
            type: String,
            required: true,
        },
        votes: {
            type: Array,
            required: true,
        },
    },
    
  methods: {
    onVote(option) {
        this.votes.every(v => {
            if(v.option===option){
                v.count++;
                this.state = 'closed'
                return false;
            }
            return true;
        });
    },
    retrieveOptions(){
        let options = []
        this.votes.forEach(vote => {
            options.push(vote.option)
        });
        return options;
    }
}
}
</script>

<style>

</style>

// frameworks-voting/src/VotingCard.svelte
<script>
    import Booth from './Booth.svelte'
    import Results from './Results.svelte'
    export let title = ''
    export let state = ''
    export let votes = []
    let options = retrieveOptions()
    function retrieveOptions(){
        let o = []
        votes.forEach(v => {
            o.push(v.option)
        });
        return o
    }
    function onVote(vote){
        votes.every(v => {
            if(v.option===vote.detail){
                v.count++;
                state = 'closed'
                return false;
            }
            return true;
        });
    }
</script>

<h3>{title}</h3>
{#if state === 'open'}
<Booth options = {options} on:vote={onVote}/>
{:else}
<Results votes = {votes}/>
{/if}
