// frameworks-voting/src/App.svelte
<script>
    import VotingCard from './VotingCard.svelte'
    import {title} from './title.js'
    import {votes} from './votes.js'
    import Form from './Form.svelte'
    let votingOpen = false
    let bundle
    function submitForm(){
        votingOpen = true
        bundle = {title: $title, state: 'open', votes: $votes}
    }
</script>
{#if votingOpen === false}
<Form on:submit={submitForm}/>
{:else}
<VotingCard title={bundle.title} state={bundle.state} votes={bundle.votes}/>
{/if}

// src/App.vue
<template>
    <div>
        <Form v-if="this.votingOpen === false" @onSubmit="onSubmit"/>
        <VotingCard v-else-if="this.votingOpen" :title = "title" :state = "votingCardState" :votes = "votes"/>
    </div>
</template>

<script>
import VotingCard from './VotingCard'
import Form from "./Form"
import store from "./store"
export default {
    name:"App",
    data: ()=>({
        votingOpen: false,
        title:'',
        votes:[],
        votingCardState: 'open'
    }),
    components: {Form, VotingCard},
    methods:{
        onSubmit(){
            this.title = store.title
            this.votes = store.votes
            this.votingOpen = true
        }
    }
}
</script>

<style>

</style>
