// frameworks-voting/src/stories/Booth.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core'

@Component({
    selector: 'Booth',
    template: `<button *ngFor="let option of options" (click)='vote.emit(option)'> {{ option }} </button>`
  })
export default class BoothComponent {
    @Input()
    options = ['test']
    @Output()
    vote = new EventEmitter()
}

// src/Booth.vue
<template>
    <div>
    <button
        v-for="option in options"
        :key="option"
        @click="$emit('onVote', option)"
        >{{ option }}</button>
    </div>
</template>

<script>
export default {
    name: 'Booth',
    props: {
    options: {
        type: Array,
        required: true,
    },
  },
}
</script>

<style>

</style>
